version: '3'

services:
  sulsuldb:
    image: mariadb:10.3
    container_name: sulsul-database
    ports:
      - "3306:3306"
    volumes:
      - ./database/:/var/lib/mysql
    environment:
      MYSQL_DATABASAE: sulsul
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: minsoo
      MYSQL_PASSWORD: 1234
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

