spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 0c67e7fe975454e2ece8b6d77efe298d
            scope:
              - profile_nickname
              - account_email
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            client-name: kakao
          naver:
            client-id: GcVDuQpzijLxjpihXQTL
            client-secret: JTM3XYwtTc
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
            client-name: naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
# kauth.kakao.com/oauth/authorize?client_id=0c67e7fe975454e2ece8b6d77efe298d&redirect_uri=http://localhost:8080/login/oauth2/code/kakao&response_type=code
# http://localhost:8080/oauth2/authorization/kakao
