spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ec2-13-125-141-181.ap-northeast-2.compute.amazonaws.com:3306/sulsulDB?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowMultiQueries=true&autoReconnection=true&characterEncoding=UTF-8
    username: ec2-user
    password: Sulsul1004~
cloud:
  aws:
    credentials:
      access-key: AKIAVPAOA5WKLKDZ5UFU
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: sulsul-media-bucket
    stack:
      auto: false